# Generated by Django 6.0.3 on 2026-04-04 14:42

import core.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0003_proxy_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, help_text='External category ID (e.g. LZT category_id)', null=True, unique=True)),
                ('name', models.CharField(help_text='Slug: steam, supercell, riot', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Display: Steam, Supercell, Riot Games', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('acronym', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='inventory.category')),
            ],
            options={
                'db_table': 'games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DropshipProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_id', models.BigIntegerField(help_text='Item ID on the source platform')),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('sold', 'Sold'), ('deleted', 'Deleted')], default='listed', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('product_title', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropship_products', to='inventory.category')),
                ('source_account', models.ForeignKey(blank=True, help_text='Source integration account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropship_products', to='integrations.integrationaccount')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropship_products', to='inventory.game')),
            ],
            options={
                'db_table': 'dropship_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlatformMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('eldorado', 'Eldorado'), ('gameboost', 'GameBoost'), ('playerauctions', 'PlayerAuctions')], max_length=30)),
                ('external_id', models.CharField(max_length=100)),
                ('external_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_mappings', to='inventory.game')),
            ],
            options={
                'db_table': 'game_platform_mappings',
                'ordering': ['game', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='OwnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('password', core.encryption.EncryptedTextField()),
                ('password_hash', models.CharField(help_text='SHA256 hash (informational, no longer part of unique key)', max_length=64)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('email_password', core.encryption.EncryptedTextField(blank=True)),
                ('email_login_link', models.CharField(blank=True, max_length=500)),
                ('security_email', models.CharField(blank=True, max_length=255)),
                ('security_email_password', core.encryption.EncryptedTextField(blank=True)),
                ('security_email_login_link', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('listed', 'Listed'), ('sold', 'Sold'), ('multiple_sold', 'Multiple Sold'), ('replaced', 'Replaced'), ('recovered', 'Recovered'), ('lost', 'Lost'), ('banned', 'Banned')], default='draft', max_length=20)),
                ('source_product_id', models.BigIntegerField(blank=True, help_text='Item ID on the source platform (e.g. LZT item_id)', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_products', to='inventory.category')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to='inventory.game')),
                ('product_origin', models.ForeignKey(blank=True, help_text='DropshipProduct this was purchased from (if dropship flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to='inventory.dropshipproduct')),
                ('source_account', models.ForeignKey(blank=True, help_text='Integration account where this product was purchased from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_products', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'owned_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dropshipproduct',
            constraint=models.UniqueConstraint(fields=('source_account', 'source_product_id'), name='unique_dropship_product'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplatformmapping',
            unique_together={('platform', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='ownedproduct',
            index=models.Index(fields=['status'], name='owned_produ_status_67f2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='ownedproduct',
            index=models.Index(fields=['-created_at'], name='owned_produ_created_51483f_idx'),
        ),
        migrations.AddIndex(
            model_name='ownedproduct',
            index=models.Index(fields=['-purchased_at'], name='owned_produ_purchas_fc4bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='ownedproduct',
            index=models.Index(fields=['source_product_id'], name='owned_produ_source__e2c739_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownedproduct',
            constraint=models.UniqueConstraint(fields=('category', 'login'), name='unique_owned_product_canonical'),
        ),
    ]
