# Generated by Django 6.0.3 on 2026-04-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ownedproduct_login_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ownedproduct',
            name='owned_produ_login_idx',
        ),
    ]
