# Generated by Django 5.0.6 on 2026-05-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_ownedproduct_ref_key"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ownedproduct",
            new_name="owned_produ_ref_key_915041_idx",
            old_name="inventory_o_ref_key_idx",
        ),
    ]
