# Generated by Django 5.0.6 on 2026-05-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_unique_service_types"),
        (
            "inventory",
            "0006_rename_inventory_o_ref_key_idx_owned_produ_ref_key_915041_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dropshipproduct",
            index=models.Index(
                fields=["source_account", "status", "last_checked_at"],
                name="ds_prod_status_checked_idx",
            ),
        ),
    ]
