# Generated by Django 6.0.3 on 2026-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_add_roblox_service_type'),
        ('inventory', '0010_backfill_ghost_dropship_products'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dropshipproduct',
            index=models.Index(fields=['status', 'game', '-created_at'], name='ds_prod_stat_game_creat_idx'),
        ),
    ]
