# Generated by Django 5.2.14 on 2026-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_dropshipproduct_ds_prod_stat_game_creat_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropshipproduct',
            name='source_product_id',
            field=models.CharField(help_text='Item ID on the source platform (numeric for LZT, UUID for Eldorado)', max_length=128),
        ),
        migrations.AlterField(
            model_name='ownedproduct',
            name='source_product_id',
            field=models.CharField(blank=True, help_text='Item ID on the source platform (e.g. LZT item_id, Eldorado UUID)', max_length=128, null=True),
        ),
    ]
