# Generated by Django 6.0.3 on 2026-04-18 — reset for 3-concept worker state model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0005_alter_servicecredential_service_type'),
        ('inventory', '0001_initial'),
        ('listings', '0002_add_admin_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Scheduler identifier, e.g. "dropship"', max_length=50, unique=True)),
                ('last_seen', models.DateTimeField(help_text='Last heartbeat timestamp — stale if >60s ago')),
                ('pid', models.IntegerField(blank=True, help_text='OS process ID (debug/monitoring)', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the scheduler process started (set by management command)', null=True)),
            ],
            options={
                'db_table': 'scheduler_heartbeats',
            },
        ),
        migrations.CreateModel(
            name='CleanerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='INTENT — should the cleaner thread run?')),
                ('disabled_reason', models.CharField(blank=True, default='', help_text='CONDITION — why disabled (empty = user choice, non-empty = system)', max_length=255)),
                ('running', models.BooleanField(default=False, help_text='ACTUAL — is the cleaner thread alive right now?')),
                ('cycle_interval', models.PositiveIntegerField(default=600, help_text='Seconds between cleaner cycles (default 10 min)')),
                ('last_cycle_at', models.DateTimeField(blank=True, help_text='When the cleaner last completed a full cycle', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_account', models.OneToOneField(help_text='Source account whose products this cleaner monitors', on_delete=django.db.models.deletion.CASCADE, related_name='cleaner_config', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'cleaner_configs',
            },
        ),
        migrations.CreateModel(
            name='DropshippingJobConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_delay', models.DecimalField(decimal_places=1, default=3.0, help_text='Seconds between marketplace POSTs', max_digits=5)),
                ('source_delay', models.DecimalField(decimal_places=1, default=1.0, help_text='Seconds between source fetches', max_digits=5)),
                ('enabled', models.BooleanField(default=True, help_text='INTENT — should the poster thread run?')),
                ('disabled_reason', models.CharField(blank=True, default='', help_text='CONDITION — why disabled (empty = user choice, non-empty = system)', max_length=255)),
                ('poster_running', models.BooleanField(default=False, help_text='ACTUAL — is the poster thread alive right now?')),
                ('poster_cycle_interval', models.PositiveIntegerField(default=300, help_text='Seconds between poster cycles (default 5 min)')),
                ('poster_last_cycle_at', models.DateTimeField(blank=True, help_text='When the poster last completed a full cycle', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropship_configs', to='inventory.game')),
                ('source_account', models.ForeignKey(help_text='Source buy account used to fetch items (e.g. LZT)', on_delete=django.db.models.deletion.CASCADE, related_name='dropship_source_configs', to='integrations.integrationaccount')),
                ('store', models.ForeignKey(help_text='Target sell account (gameboost, eldorado, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='dropship_target_configs', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'dropshipping_job_configs',
                'unique_together': {('source_account', 'store', 'game')},
            },
        ),
        migrations.CreateModel(
            name='DropshipTargetURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='LZT filter URL (e.g. https://lzt.market/fortnite?pmin=5)', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('multiplier_low', models.DecimalField(decimal_places=2, default=2.0, help_text='Multiplier for price <= $10', max_digits=5)),
                ('multiplier_mid', models.DecimalField(decimal_places=2, default=1.8, help_text='Multiplier for $10 < price <= $100', max_digits=5)),
                ('multiplier_high', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for price > $100', max_digits=5)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, help_text='Floor price', max_digits=10)),
                ('forced_ending', models.DecimalField(blank=True, decimal_places=2, default=0.99, help_text='Force cents ending (e.g. 0.99). Null = disabled.', max_digits=3, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('items_found', models.IntegerField(default=0)),
                ('items_posted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_urls', to='posting.dropshippingjobconfig')),
            ],
            options={
                'db_table': 'dropship_target_urls',
            },
        ),
        migrations.CreateModel(
            name='PostingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Store slug-keyed pricing/config snapshot from UI')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_jobs', to='inventory.game')),
                ('source_account', models.ForeignKey(blank=True, help_text='Fallback account for resolving missing products (e.g. LZT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_jobs_as_source', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'posting_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='stock_post, dropship_poster, dropship_cleaner', max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_logs', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'posting_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=30)),
                ('multiplier_low', models.DecimalField(decimal_places=2, default=2.0, help_text='Multiplier for price <= $10', max_digits=5)),
                ('multiplier_mid', models.DecimalField(decimal_places=2, default=1.8, help_text='Multiplier for $10 < price <= $100', max_digits=5)),
                ('multiplier_high', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for price > $100', max_digits=5)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, help_text='Floor price — result never goes below this', max_digits=10)),
                ('forced_ending', models.DecimalField(blank=True, decimal_places=2, default=0.99, help_text='Force cents ending (e.g. 0.99). Null = disabled.', max_digits=3, null=True)),
                ('sub_platform', models.CharField(blank=True, help_text='Last selected sub-platform (PC/PSN/Xbox/Auto)', max_length=20)),
                ('account_type', models.CharField(blank=True, help_text='Last selected account type', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_defaults', to='inventory.game')),
            ],
            options={
                'db_table': 'posting_defaults',
                'unique_together': {('game', 'marketplace')},
            },
        ),
        migrations.CreateModel(
            name='PostingJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', help_text='Login identifier — always populated, primary key for tracking', max_length=255)),
                ('marketplace', models.CharField(help_text='Denormalized from store.provider for query performance', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posting.postingjob')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_items', to='listings.listing')),
                ('owned_product', models.ForeignKey(blank=True, help_text='Resolved after job creation; null until orchestrator resolves', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_items', to='inventory.ownedproduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_items', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'posting_job_items',
                'indexes': [models.Index(fields=['status'], name='posting_job_status_4a498e_idx'), models.Index(fields=['job', 'status'], name='posting_job_job_id_62051c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubplatformLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_platform', models.CharField(help_text='PC, PSN, Xbox, etc.', max_length=20)),
                ('max_offers', models.IntegerField(help_text='Maximum offers allowed on this sub-platform')),
                ('stock_reserve', models.IntegerField(default=0, help_text='Slots reserved for stock (dropship cannot use these)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subplatform_limits', to='inventory.game')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subplatform_limits', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'subplatform_limits',
                'unique_together': {('store', 'game', 'sub_platform')},
            },
        ),
    ]
