# Generated by Django 6.0.3 on 2026-05-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_add_google_sheets_service_type'),
        ('inventory', '0004_fee_rule'),
        ('listings', '0002_add_admin_indexes'),
        ('posting', '0002_postinglog_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('append', 'Append Credentials'), ('clone', 'Clone Offer')], help_text='append (Eldorado/Gameboost) or clone (PlayerAuctions)', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('depleted', 'Depleted')], default='active', max_length=10)),
                ('threshold', models.PositiveIntegerField(default=10, help_text='Trigger replenish when remote credential count drops below this')),
                ('target_count', models.PositiveIntegerField(default=50, help_text='Fill up to this many credentials per replenish cycle')),
                ('max_concurrent', models.PositiveIntegerField(default=1, help_text='PA clone strategy: max simultaneous offers from this pool')),
                ('current_remote_count', models.IntegerField(blank=True, help_text='Last known credential count on the remote offer', null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time remote count was checked', null=True)),
                ('last_replenished_at', models.DateTimeField(blank=True, help_text='Last time credentials were pushed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_pools', to='inventory.game')),
                ('listing', models.ForeignKey(help_text='The offer to restock', on_delete=django.db.models.deletion.CASCADE, related_name='offer_pools', to='listings.listing')),
                ('store', models.ForeignKey(help_text='Marketplace account where the offer lives', on_delete=django.db.models.deletion.CASCADE, related_name='offer_pools', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'offer_pools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferPoolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('pushed', 'Pushed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('target_offer_id', models.CharField(blank=True, help_text='Remote offer ID this credential was pushed to (relevant for PA clones)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Push priority (lower = pushed first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_items', to='inventory.ownedproduct')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posting.offerpool')),
            ],
            options={
                'db_table': 'offer_pool_items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferPoolActiveOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_listing_id', models.CharField(help_text='Remote offer ID on the marketplace', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('failed', 'Failed'), ('delisted', 'Delisted')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_active_offers', to='listings.listing')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_offers', to='posting.offerpool')),
                ('pool_item', models.ForeignKey(blank=True, help_text='Which pool item (credential) was used for this offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_offers', to='posting.offerpoolitem')),
            ],
            options={
                'db_table': 'offer_pool_active_offers',
            },
        ),
        migrations.AddConstraint(
            model_name='offerpool',
            constraint=models.UniqueConstraint(fields=('listing',), name='unique_pool_per_listing'),
        ),
        migrations.AddIndex(
            model_name='offerpoolitem',
            index=models.Index(fields=['pool', 'status'], name='offer_pool__pool_id_ac5cc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerpoolitem',
            constraint=models.UniqueConstraint(fields=('pool', 'owned_product'), name='unique_pool_owned_product'),
        ),
        migrations.AddIndex(
            model_name='offerpoolactiveoffer',
            index=models.Index(fields=['pool', 'status'], name='offer_pool__pool_id_58d104_idx'),
        ),
    ]
