# Generated by Django 6.0.3 on 2026-05-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_add_offer_pool_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshiptargeturl',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.87, help_text='USD→EUR conversion rate for Gameboost. Null = no conversion.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='postingdefault',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.87, help_text='USD→EUR conversion rate for Gameboost. Null = no conversion.', max_digits=6, null=True),
        ),
    ]
