# Generated by Codex on 2026-05-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.posting.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_rename_inventory_o_ref_key_idx_owned_produ_ref_key_915041_idx'),
        ('posting', '0004_add_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingImagePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to=apps.posting.models.posting_image_preset_upload_to)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_image_presets', to='inventory.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_image_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posting_image_presets',
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='postingimagepreset',
            constraint=models.UniqueConstraint(fields=('user', 'game', 'sha256'), name='unique_posting_image_preset_hash'),
        ),
        migrations.AddIndex(
            model_name='postingimagepreset',
            index=models.Index(fields=['user', 'game', 'is_active'], name='posting_img_user_game_idx'),
        ),
    ]
