# Generated by Django 6.0.3 on 2026-05-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_posting_image_preset'),
        ('posting', '0007_cosmetic_list'),
    ]

    operations = [
    ]
