# Generated by Django 6.0.3 on 2026-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_merge_0005_posting_image_preset_0007_cosmetic_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cosmeticlist',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive lists are skipped during context building.'),
        ),
        migrations.AlterField(
            model_name='cosmeticlist',
            name='items',
            field=models.JSONField(default=list, help_text='List of item names to match against, e.g. ["Renegade Raider", "Black Knight"]'),
        ),
        migrations.AlterField(
            model_name='cosmeticlist',
            name='match_field',
            field=models.CharField(default='cosmetic_titles', help_text='Account field to match against (e.g. cosmetic_titles)', max_length=50),
        ),
        migrations.AlterField(
            model_name='cosmeticlist',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Processing order (lower = first). Higher priority lists claim items first.'),
        ),
    ]
