# Generated by Django 6.0.3 on 2026-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0012_drop_subplatform_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingdefault',
            name='variant',
            field=models.CharField(blank=True, help_text='Last selected variant slug (pc/psn/xbox/auto)', max_length=20),
        ),
    ]
