# Generated by Django 6.0.3 on 2026-06-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_seed_missing_game_platform_mappings'),
        ('posting', '0013_alter_postingdefault_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.JSONField(help_text='List of CredentialFieldSchema dicts: [{key, label, required, role}, ...]')),
                ('format_templates', models.JSONField(blank=True, default=dict, help_text='Marketplace-keyed format templates: {eldorado: "...", gameboost: "...", playerauctions: {...}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_specs', to='inventory.game')),
                ('variant', models.ForeignKey(blank=True, help_text='If set, this spec applies to a specific variant. NULL = game default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credential_specs', to='posting.gamevariant')),
            ],
            options={
                'db_table': 'credential_specs',
                'ordering': ['game', 'name'],
            },
        ),
        migrations.AddField(
            model_name='offerpool',
            name='credential_spec',
            field=models.ForeignKey(blank=True, help_text='Credential field definition + format templates. NULL = use resolver chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='posting.credentialspec'),
        ),
        migrations.AddConstraint(
            model_name='credentialspec',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('game',), name='unique_game_default_spec'),
        ),
        migrations.AddConstraint(
            model_name='credentialspec',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('variant',), name='unique_variant_spec'),
        ),
    ]
