# Generated by Django 6.0.3 on 2026-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0014_credential_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialspec',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
