# Generated by Django 6.0.3 on 2026-06-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0015_credential_spec_name_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpoolitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('pushed', 'Pushed'), ('failed', 'Failed'), ('consumed', 'Consumed')], default='pending', max_length=10),
        ),
    ]
