# Generated by Django 6.0.3 on 2026-06-24 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_token_api_client'),
        ('inventory', '0009_remove_new_world_gameboost_mapping'),
        ('listings', '0006_add_listed_at_removed_at_indexes'),
        ('posting', '0018_seed_new_game_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolSaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pool_sale_events',
            },
        ),
        migrations.AddField(
            model_name='offerpool',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offerpool',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_pools', to='posting.gamevariant'),
        ),
        migrations.AddField(
            model_name='offerpoolitem',
            name='claim_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offerpoolitem',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerpoolitem',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerpoolitem',
            name='failure_stage',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='offerpoolitem',
            name='remote_credential_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offerpoolitem',
            name='remote_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='credential_spec',
            field=models.ForeignKey(blank=True, help_text='Credential field definition + format templates. NULL = use resolver chain.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='posting.credentialspec'),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_pools', to='inventory.game'),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Deprecated: use pool_offers instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_pools', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived'), ('depleted', 'Depleted (Legacy)')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Deprecated: derive store from PoolOffer.listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_pools', to='integrations.integrationaccount'),
        ),
        migrations.AlterField(
            model_name='offerpool',
            name='strategy',
            field=models.CharField(blank=True, choices=[('append', 'Append Credentials'), ('clone', 'Clone Offer')], help_text='Deprecated: strategy is configured per PoolOffer', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offerpoolactiveoffer',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_active_offers', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='offerpoolactiveoffer',
            name='pool',
            field=models.ForeignKey(help_text='Deprecated: derive through pool_offer.pool', on_delete=django.db.models.deletion.PROTECT, related_name='active_offers', to='posting.offerpool'),
        ),
        migrations.AlterField(
            model_name='offerpoolactiveoffer',
            name='pool_item',
            field=models.ForeignKey(blank=True, help_text='Which pool item (credential) was used for this offer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_offers', to='posting.offerpoolitem'),
        ),
        migrations.AlterField(
            model_name='offerpoolitem',
            name='owned_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_items', to='inventory.ownedproduct'),
        ),
        migrations.AlterField(
            model_name='offerpoolitem',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='posting.offerpool'),
        ),
        migrations.CreateModel(
            name='PoolOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('append', 'Append Credentials'), ('clone', 'Clone Offer')], max_length=10)),
                ('target_count', models.PositiveIntegerField(default=5)),
                ('threshold', models.PositiveIntegerField(default=2)),
                ('max_concurrent', models.PositiveIntegerField(blank=True, null=True)),
                ('current_remote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_replenished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('detached', 'Detached'), ('error', 'Error')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pool_offer', to='listings.listing')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_offers', to='posting.offerpool')),
            ],
            options={
                'db_table': 'pool_offers',
            },
        ),
        migrations.CreateModel(
            name='PoolDispatchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation', models.CharField(choices=[('push', 'Push'), ('remove', 'Remove'), ('reconcile', 'Reconcile')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unknown', 'Unknown Remote Outcome'), ('rolled_back', 'Rolled Back')], default='pending', max_length=16)),
                ('remote_offer_id', models.CharField(blank=True, max_length=255)),
                ('remote_credential_id', models.CharField(blank=True, max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_attempts', to='posting.offerpoolitem')),
                ('pool_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_attempts', to='posting.pooloffer')),
            ],
            options={
                'db_table': 'pool_dispatch_attempts',
            },
        ),
        migrations.AddField(
            model_name='offerpoolactiveoffer',
            name='pool_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_offers', to='posting.pooloffer'),
        ),
        migrations.AddField(
            model_name='offerpoolitem',
            name='pool_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='posting.pooloffer'),
        ),
        migrations.AddIndex(
            model_name='offerpoolactiveoffer',
            index=models.Index(fields=['pool_offer', 'status'], name='pool_active_offer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offerpoolitem',
            index=models.Index(fields=['pool', 'status', 'pool_offer', 'order'], name='pool_item_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='offerpoolitem',
            index=models.Index(fields=['pool_offer', 'status'], name='pool_item_offer_status_idx'),
        ),
        migrations.AddField(
            model_name='poolsaleevent',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_sale_events', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='poolsaleevent',
            name='pool_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_events', to='posting.pooloffer'),
        ),
        migrations.AddIndex(
            model_name='pooloffer',
            index=models.Index(fields=['status', 'pool'], name='pool_offer_status_pool_idx'),
        ),
        migrations.AddIndex(
            model_name='pooloffer',
            index=models.Index(fields=['last_checked_at'], name='pool_offer_checked_idx'),
        ),
        migrations.AddConstraint(
            model_name='pooloffer',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__lte', models.F('target_count'))), name='pool_offer_threshold_lte_target'),
        ),
        migrations.AddIndex(
            model_name='pooldispatchattempt',
            index=models.Index(fields=['pool_offer', 'status'], name='pool_attempt_offer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pooldispatchattempt',
            index=models.Index(fields=['item', '-created_at'], name='pool_attempt_item_created_idx'),
        ),
        migrations.AddIndex(
            model_name='poolsaleevent',
            index=models.Index(fields=['pool_offer', '-created_at'], name='pool_sale_offer_created_idx'),
        ),
    ]
