# Generated by Django 6.0.3 on 2026-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_new_world_gameboost_mapping'),
        ('posting', '0021_adopt_pa_source_offers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offerpoolitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), ('pool_offer__isnull', True), _connector='OR'), name='pending_pool_item_unassigned'),
        ),
        migrations.AddConstraint(
            model_name='offerpoolitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['queued', 'pushed', 'consumed']), _negated=True), ('pool_offer__isnull', False), _connector='OR'), name='assigned_pool_item_has_offer'),
        ),
        migrations.AddConstraint(
            model_name='offerpoolitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'queued'), _negated=True), ('claim_token__isnull', False), _connector='OR'), name='queued_pool_item_has_claim'),
        ),
    ]
