# Generated by Django 6.0.3 on 2026-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_add_listed_at_removed_at_indexes'),
        ('posting', '0022_unified_pool_item_state_constraints'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pooloffer',
            constraint=models.CheckConstraint(condition=models.Q(('target_count__gte', 1), ('threshold__gte', 1)), name='pool_offer_positive_threshold_target'),
        ),
        migrations.AddConstraint(
            model_name='pooloffer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_concurrent__isnull', True), ('strategy', 'append')), models.Q(('max_concurrent__isnull', False), ('max_concurrent__lte', 10), ('strategy', 'clone'), ('target_count__lte', models.F('max_concurrent'))), _connector='OR'), name='pool_offer_strategy_capacity_valid'),
        ),
    ]
