# Generated by Django 5.2.14 on 2026-07-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0027_pool_dispatch_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingdefault',
            name='seller_username',
            field=models.CharField(blank=True, default='', help_text='Eldorado seller username to filter by (e.g. OdbougShop). Empty = all sellers.', max_length=100),
        ),
        migrations.AlterField(
            model_name='dropshiptargeturl',
            name='url',
            field=models.URLField(help_text='Source filter URL or query string (e.g. gameId=259&category=CustomItem)', max_length=500),
        ),
    ]
