# Generated by Django 5.2.14 on 2026-07-09 14:18
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ("posting", "0029_backfill_cleaner_configs"),
    ]
    operations = [
        migrations.AddField(
            model_name="dropshiptargeturl",
            name="seller_uuid",
            field=models.CharField(
                blank=True, default=None,
                help_text="Eldorado userId UUID for this seller (resolved automatically, enables server-side filtering).",
                max_length=100, null=True,
            ),
        ),
    ]
