# Generated by Django 5.2.14 on 2026-10-01 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_dropship_target_seller_username(apps, schema_editor):
    """Repair a historical model/migration gap without duplicating a live column."""
    target_url = apps.get_model('posting', 'DropshipTargetURL')
    table_name = target_url._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name,
            )
        }
    if 'seller_username' not in columns:
        field = models.CharField(
            blank=True,
            default=None,
            help_text='If set, only source items from this specific Eldorado seller username.',
            max_length=100,
            null=True,
        )
        field.set_attributes_from_name('seller_username')
        schema_editor.add_field(
            target_url,
            field,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0034_offer_pool_item_live_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The deployed database already has this field, but its historical
        # migration state was missing it.  Keep fresh environments correct
        # while making production application a no-op for the existing column.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_dropship_target_seller_username,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='dropshiptargeturl',
                    name='seller_username',
                    field=models.CharField(blank=True, default=None, help_text='If set, only source items from this specific Eldorado seller username.', max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ManualFaultyPoolTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pool_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_faulty_transfer', to='posting.offerpoolitem')),
            ],
            options={
                'db_table': 'manual_faulty_pool_transfers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='manual_faul_created_ccfeee_idx')],
            },
        ),
    ]
