# Generated by Django 6.0.3 on 2026-06-24 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobuxCrateOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roblox_username', models.CharField(max_length=50)),
                ('roblox_user_id', models.BigIntegerField(blank=True, null=True)),
                ('place_id', models.BigIntegerField()),
                ('place_name', models.CharField(blank=True, max_length=200)),
                ('robux_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rbxcrate_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robuxcrate_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
