# Generated by Django 5.2.14 on 2026-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_simplify_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="robuxcratebatch",
            name="auto_place",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="robuxcratebatch",
            name="place_attempt_index",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Index into place_candidates of the currently active place",
            ),
        ),
        migrations.AddField(
            model_name="robuxcratebatch",
            name="place_candidates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of {place_id, name} candidates tried in auto-place mode",
            ),
        ),
    ]
