# Generated by Django 5.2.14 on 2026-07-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_fee_rule'),
        ('tools', '0005_robuxcratebatch_auto_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobuxAutoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('awaiting_username', 'Awaiting Username'), ('username_received', 'Username Received'), ('order_created', 'Order Created'), ('place_lookup_failed', 'Place Lookup Failed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='awaiting_username', max_length=30)),
                ('roblox_username', models.CharField(blank=True, max_length=100)),
                ('telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('username_received_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_orders', to='tools.robuxcratebatch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robux_auto_order', to='orders.order')),
            ],
            options={
                'db_table': 'tools_robux_auto_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
