# Generated by Django 5.2.14 on 2026-07-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_dropshipproduct_ds_prod_stat_game_creat_idx'),
        ('orders', '0003_fee_rule'),
        ('tools', '0006_robux_auto_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshipDeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending_eldorado', 'Pending Eldorado Buy'), ('eldorado_done', 'Eldorado Bought & Sent'), ('fully_delivered', 'Fully Delivered'), ('cancelled', 'Cancelled')], default='pending_eldorado', max_length=30)),
                ('telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('eldorado_done_by', models.CharField(blank=True, max_length=100)),
                ('eldorado_done_at', models.DateTimeField(blank=True, null=True)),
                ('gb_done_by', models.CharField(blank=True, max_length=100)),
                ('gb_done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropship_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_trackings', to='inventory.dropshipproduct')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropship_delivery_tracking', to='orders.order')),
            ],
            options={
                'db_table': 'tools_dropship_delivery_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state'], name='idx_ddt_state'), models.Index(fields=['created_at'], name='idx_ddt_created')],
            },
        ),
    ]
