# Generated by Django 6.0.3 on 2026-04-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0003_proxy_model'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_instant', models.BooleanField(default=True, help_text='True=OwnedProduct (instant), False=DropshipProduct (manual)')),
                ('store_listing_id', models.CharField(help_text='Listing ID on the platform (UUID for Eldorado, numeric for others)', max_length=255)),
                ('product_category', models.CharField(choices=[('accounts', 'Accounts'), ('items', 'Items'), ('currency', 'Currency'), ('gift_card', 'Gift Card'), ('top_up', 'Top Up')], default='accounts', max_length=20)),
                ('sub_platform', models.CharField(blank=True, help_text='pc, psn, xbox, ios, android, switch, main', max_length=20)),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('paused', 'Paused'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='listed', max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropship_product', models.ForeignKey(blank=True, help_text='Dropship flow (null if instant)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='inventory.dropshipproduct')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='inventory.game')),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingOwnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_owned_products', to='listings.listing')),
                ('owned_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_owned_products', to='inventory.ownedproduct')),
            ],
            options={
                'db_table': 'listing_owned_products',
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listings_status_c3eaec_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['store_listing_id'], name='listings_store_l_e302bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('integration_account', 'store_listing_id'), name='unique_account_listing'),
        ),
        migrations.AddConstraint(
            model_name='listingownedproduct',
            constraint=models.UniqueConstraint(fields=('listing', 'owned_product'), name='unique_listing_owned_product'),
        ),
    ]
