# Generated by Django 6.0.3 on 2026-04-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_proxy_model'),
        ('inventory', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_created_4615f6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['integration_account', '-created_at'], name='listings_integra_ad75a4_idx'),
        ),
    ]
