# Generated by Django 6.0.3 on 2026-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_sub_platform_to_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='variant',
            field=models.CharField(blank=True, help_text='Canonical variant slug: pc, psn, xbox, na, euw, etc.', max_length=20),
        ),
    ]
