# Generated by Django 6.0.3 on 2026-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_token_api_client'),
        ('inventory', '0008_seed_missing_game_platform_mappings'),
        ('listings', '0005_alter_listing_variant_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-listed_at'], name='listings_listed__69d568_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-removed_at'], name='listings_removed_9cab96_idx'),
        ),
    ]
