# Generated by Django 6.0.3 on 2026-03-22 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('orders', 'Orders'), ('listings', 'Listings')], max_length=20)),
                ('remote_id', models.CharField(help_text='ID of this item on the remote provider', max_length=255)),
                ('payload', models.JSONField(help_text='Raw JSON response from provider')),
                ('payload_hash', models.CharField(help_text='SHA-256 of serialised payload for change detection', max_length=64)),
                ('first_seen_at', models.DateTimeField(help_text='When this remote item was first ingested')),
                ('last_seen_at', models.DateTimeField(help_text='When this remote item was last seen in a fetch')),
                ('fetched_at', models.DateTimeField(help_text='Timestamp of the fetch that last wrote this row')),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('parse_error', models.TextField(blank=True, help_text='Traceback or message when parse_status is failed')),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Optional metadata (provider page info, fetch context, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_payloads', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'sync_raw_payloads',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['resource_type', 'parse_status'], name='sync_raw_pa_resourc_697192_idx'), models.Index(fields=['integration_account', 'resource_type', 'parse_status'], name='sync_raw_pa_integra_34ce5f_idx'), models.Index(fields=['fetched_at'], name='sync_raw_pa_fetched_2d7996_idx')],
                'constraints': [models.UniqueConstraint(fields=('integration_account', 'resource_type', 'remote_id'), name='unique_account_resource_remote')],
            },
        ),
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('orders', 'Orders'), ('listings', 'Listings')], max_length=20)),
                ('mode', models.CharField(choices=[('backfill', 'Backfill'), ('incremental', 'Incremental')], max_length=20)),
                ('cursor', models.TextField(blank=True, help_text='Opaque cursor value for the next page/batch (provider-specific)')),
                ('last_seen_remote_id', models.CharField(blank=True, help_text='Last remote ID successfully ingested', max_length=255)),
                ('last_seen_remote_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of the last remote item ingested', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When the last sync run started for this checkpoint', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stale', 'Stale')], default='active', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Provider-specific checkpoint context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_checkpoints', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'sync_checkpoints',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('integration_account', 'resource_type', 'mode'), name='unique_account_resource_mode')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('orders', 'Orders'), ('listings', 'Listings')], max_length=20)),
                ('mode', models.CharField(choices=[('backfill', 'Backfill'), ('incremental', 'Incremental')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Run-level metadata (error summary, last page, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'sync_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['integration_account', 'resource_type'], name='sync_runs_integra_c62dba_idx'), models.Index(fields=['status'], name='sync_runs_status_08b30a_idx'), models.Index(fields=['-started_at'], name='sync_runs_started_503e34_idx')],
            },
        ),
    ]
