# Generated by Django 6.0.3 on 2026-03-31 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationaccount_provider'),
        ('inventory', '0001_initial'),
        ('listings', '0001_initial'),
        ('orders', '0001_initial'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpayload',
            name='resource_type',
            field=models.CharField(choices=[('orders', 'Orders'), ('listings', 'Listings'), ('owned_products', 'Owned Products')], max_length=20),
        ),
        migrations.AlterField(
            model_name='synccheckpoint',
            name='resource_type',
            field=models.CharField(choices=[('orders', 'Orders'), ('listings', 'Listings'), ('owned_products', 'Owned Products')], max_length=20),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='resource_type',
            field=models.CharField(choices=[('orders', 'Orders'), ('listings', 'Listings'), ('owned_products', 'Owned Products')], max_length=20),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Sync task identifier (e.g. lzt_sync, offer_sync, reconcile)', max_length=100)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('message', models.TextField(help_text='Human-readable summary of what happened')),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Machine-readable details (counters, IDs, tracebacks)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='integrations.integrationaccount')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='listings.listing')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='orders.order')),
                ('owned_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='inventory.ownedproduct')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='sync.syncrun')),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sync_logs_created_a9c4e8_idx'), models.Index(fields=['task_name', '-created_at'], name='sync_logs_task_na_cfc366_idx'), models.Index(fields=['level', '-created_at'], name='sync_logs_level_4d29c2_idx')],
            },
        ),
    ]
