# Generated by Django 5.0.6 on 2026-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_sync_log_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawpayload",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("orders", "Orders"),
                    ("listings", "Listings"),
                    ("owned_products", "Owned Products"),
                    ("reviews", "Reviews"),
                    ("notifications", "Notifications"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="synccheckpoint",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("orders", "Orders"),
                    ("listings", "Listings"),
                    ("owned_products", "Owned Products"),
                    ("reviews", "Reviews"),
                    ("notifications", "Notifications"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="syncrun",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("orders", "Orders"),
                    ("listings", "Listings"),
                    ("owned_products", "Owned Products"),
                    ("reviews", "Reviews"),
                    ("notifications", "Notifications"),
                ],
                max_length=20,
            ),
        ),
    ]
