# Generated by Django 6.0.3 on 2026-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_add_historical_orders_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier (e.g. sync.reconcile, sync.review_monitor)', max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck to disable this sync feature at runtime')),
                ('description', models.CharField(blank=True, help_text='Human-readable description of what this flag controls', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Feature Flag',
                'verbose_name_plural': 'Sync Feature Flags',
                'db_table': 'sync_feature_flags',
                'ordering': ['key'],
            },
        ),
    ]
