# Generated by Django 6.0.3 on 2026-06-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_seed_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncfeatureflag',
            name='value',
            field=models.JSONField(blank=True, help_text='Optional config value (e.g. {"interval_minutes": 30})', null=True),
        ),
    ]
