# Generated by Django 5.2.14 on 2026-06-29 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0010_add_roblox_service_type"),
        ("sync", "0007_add_value_to_syncfeatureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="EldoradoReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        help_text="orderReview.id on Eldorado", max_length=255
                    ),
                ),
                (
                    "feedback_rating",
                    models.CharField(
                        help_text="Negative / Positive / Neutral", max_length=20
                    ),
                ),
                (
                    "game_category_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("review_message", models.TextField(blank=True, default="")),
                ("feedback_tags", models.JSONField(blank=True, default=list)),
                (
                    "was_initial_rating_positive",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "buyer_masked_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="orderReview.date (parsed; raw value kept in `raw`)",
                        null=True,
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full review item payload as returned by the API",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="True once a Telegram alert was sent (or the row was seeded)",
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notify_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of Telegram send attempts (bounds retries on failure)",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        help_text="When the monitor first ingested this review"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eldorado_reviews",
                        to="integrations.integrationaccount",
                    ),
                ),
            ],
            options={
                "db_table": "eldorado_reviews",
                "ordering": ["-review_date"],
                "indexes": [
                    models.Index(
                        fields=["integration_account", "feedback_rating"],
                        name="eldorado_re_integra_91d575_idx",
                    ),
                    models.Index(
                        fields=["integration_account", "notified"],
                        name="eldorado_re_integra_cf1337_idx",
                    ),
                    models.Index(
                        fields=["review_date"], name="eldorado_re_review__94c80a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("integration_account", "remote_id"),
                        name="unique_eldorado_review",
                    )
                ],
            },
        ),
    ]
