# Generated by Django 5.2.14 on 2026-07-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_eldoradoreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpayload',
            name='resource_type',
            field=models.CharField(choices=[('orders', 'Orders'), ('item_orders', 'Item Orders'), ('historical_orders', 'Historical Orders'), ('listings', 'Listings'), ('owned_products', 'Owned Products'), ('reviews', 'Reviews'), ('notifications', 'Notifications')], max_length=20),
        ),
        migrations.AlterField(
            model_name='synccheckpoint',
            name='resource_type',
            field=models.CharField(choices=[('orders', 'Orders'), ('item_orders', 'Item Orders'), ('historical_orders', 'Historical Orders'), ('listings', 'Listings'), ('owned_products', 'Owned Products'), ('reviews', 'Reviews'), ('notifications', 'Notifications')], max_length=20),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='resource_type',
            field=models.CharField(choices=[('orders', 'Orders'), ('item_orders', 'Item Orders'), ('historical_orders', 'Historical Orders'), ('listings', 'Listings'), ('owned_products', 'Owned Products'), ('reviews', 'Reviews'), ('notifications', 'Notifications')], max_length=20),
        ),
    ]
