# Generated by Django 6.0.3 on 2026-04-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0003_proxy_model'),
        ('inventory', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_instant', models.BooleanField(default=True, help_text='True=instant delivery, False=manual/dropship')),
                ('product_category', models.CharField(choices=[('accounts', 'Accounts'), ('items', 'Items'), ('currency', 'Currency'), ('gift_card', 'Gift Card'), ('top_up', 'Top Up')], default='accounts', max_length=20)),
                ('store_order_id', models.CharField(help_text='Order ID on the platform', max_length=255)),
                ('store_listing_id', models.CharField(blank=True, help_text='Listing ID on the platform (for cross-referencing)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('our_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Platform commission/fee', max_digits=10, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropship_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.dropshipproduct')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.game')),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='integrations.integrationaccount')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='listings.listing')),
                ('owned_product', models.ForeignKey(blank=True, help_text='Instant: set on creation. Manual: set after fulfillment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.ownedproduct')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['store_order_id'], name='orders_store_o_b3eecb_idx')],
                'constraints': [models.UniqueConstraint(fields=('integration_account', 'store_order_id'), name='unique_account_order')],
            },
        ),
    ]
