# Generated by Django 6.0.3 on 2026-04-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_proxy_model'),
        ('inventory', '0001_initial'),
        ('listings', '0002_add_admin_indexes'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_created_b25042_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-sold_at'], name='orders_sold_at_dcde85_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['integration_account', '-created_at'], name='orders_integra_fb1969_idx'),
        ),
    ]
