# Generated by Django 6.0.3 on 2026-04-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fee_rule'),
        ('orders', '0002_add_admin_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('lzt', 'LZT Market'), ('g2g', 'G2G'), ('eldorado', 'Eldorado'), ('gameboost', 'Gameboost'), ('playerauctions', 'PlayerAuctions')], max_length=20)),
                ('product_category', models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('items', 'Items'), ('currency', 'Currency'), ('gift_card', 'Gift Card'), ('top_up', 'Top Up')], help_text='Empty = default for all categories', max_length=20)),
                ('fee_type', models.CharField(choices=[('sale', 'Sale'), ('withdraw', 'Withdraw')], default='sale', max_length=10)),
                ('fee_percent', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g. 10.00 = 10%)', max_digits=5)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount per order (e.g. completion fee €0.99)', max_digits=10)),
                ('flat_fee_currency', models.CharField(default='EUR', help_text='Currency for the flat fee amount', max_length=3)),
                ('effective_from', models.DateField(help_text='Start date when this rule becomes effective')),
                ('effective_until', models.DateField(blank=True, help_text='Empty = still active', null=True)),
                ('note', models.TextField(blank=True, help_text='Description (e.g. source URL, reason for change)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, help_text='Empty = default for all games', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='inventory.game')),
            ],
            options={
                'db_table': 'fee_rules',
                'ordering': ['marketplace', 'fee_type', '-effective_from'],
                'indexes': [models.Index(fields=['marketplace', 'fee_type', 'effective_from'], name='fee_rule_lookup_idx')],
            },
        ),
    ]
