# Generated by Django 5.2.14 on 2026-07-31 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_seed_eldorado_forza_mappings"),
        ("orders", "0003_fee_rule"),
        ("posting", "0032_pool_sale_event_item_attribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderReplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("employee_name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_in",
                        to="inventory.ownedproduct",
                    ),
                ),
                (
                    "old_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_out",
                        to="inventory.ownedproduct",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacements",
                        to="orders.order",
                    ),
                ),
                (
                    "pool_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="posting.offerpoolitem",
                    ),
                ),
            ],
            options={
                "db_table": "order_replacements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="order_repla_order_i_a129ca_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="order_repla_created_2a781d_idx"
                    ),
                ],
            },
        ),
    ]
