# Generated by Django 6.0.3 on 2026-03-18 03:02

import core.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Account name, e.g. "store4gamers"', max_length=100)),
                ('provider', models.CharField(choices=[('lzt', 'LZT Market'), ('g2g', 'G2G'), ('eldorado', 'Eldorado'), ('gameboost', 'Gameboost')], help_text='Which marketplace provider this account uses', max_length=50)),
                ('slug', models.SlugField(help_text='e.g. "eldorado-store4gamers"', unique=True)),
                ('role', models.CharField(choices=[('buy', 'Buy (Source)'), ('sell', 'Sell (Target)'), ('both', 'Both')], default='sell', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='integrations.accountgroup')),
            ],
            options={
                'db_table': 'integration_accounts',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', core.encryption.EncryptedJSONField(default=dict, help_text='Provider-specific credentials (encrypted at rest)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the current access token expires (for OAuth/session-based providers)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'integration_credentials',
            },
        ),
    ]
