# Generated by Django 6.0.3 on 2026-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationaccount',
            name='provider',
            field=models.CharField(choices=[('lzt', 'LZT Market'), ('g2g', 'G2G'), ('eldorado', 'Eldorado'), ('gameboost', 'Gameboost'), ('playerauctions', 'PlayerAuctions')], help_text='Which marketplace provider this account uses', max_length=50),
        ),
    ]
