# Generated by Django 5.0.6 on 2026-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_alter_servicecredential_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecredential",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("proxy", "Proxy Provider"),
                    ("image", "Image Hosting"),
                    ("storage", "Cloud Storage"),
                    ("game-service", "Game Service"),
                    ("notification", "Notification Service"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
