# Generated by Django 6.0.3 on 2026-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_servicecredential_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecredential',
            name='service_type',
            field=models.CharField(choices=[('proxy', 'Proxy Provider'), ('image', 'Image Hosting'), ('storage', 'Cloud Storage'), ('game-service', 'Game Service'), ('notification', 'Notification Service'), ('email', 'Email Service'), ('google-sheets', 'Google Sheets'), ('other', 'Other')], max_length=50),
        ),
    ]
