# Generated by Django 6.0.3 on 2026-05-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_unique_service_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client identifier, e.g. "order-tracker-server"', max_length=100)),
                ('api_key_hash', models.CharField(editable=False, help_text='SHA-256 hex digest of the API key', max_length=64, unique=True)),
                ('api_key_prefix', models.CharField(editable=False, help_text='First 8 chars of key (display/debug only)', max_length=8)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='IP addresses or CIDR ranges. Ignored if allow_any_ip=True.')),
                ('allow_any_ip', models.BooleanField(default=False, help_text='If True, any IP is accepted. If False and allowed_ips is empty, NO IP is accepted.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'integrations_token_api_client',
            },
        ),
    ]
