# Generated by Django 6.0.3 on 2026-06-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_token_api_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecredential',
            name='service_type',
            field=models.CharField(choices=[('proxyline', 'Proxyline'), ('imgur', 'Imgur'), ('imageshack', 'ImageShack'), ('dropbox', 'Dropbox'), ('robuxcrate', 'RobuxCrate'), ('roblox', 'Roblox API'), ('telegram', 'Telegram'), ('firstmail', 'FirstMail'), ('google-sheets', 'Google Sheets'), ('other', 'Other')], max_length=50),
        ),
    ]
